<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11489" started-at="2018-12-14T09:26:42Z" finished-at="2018-12-14T09:26:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11489" started-at="2018-12-14T09:26:42Z" finished-at="2018-12-14T09:26:53Z">
      <class name="com.testPackage.GoogleTitleTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.testPackage.GoogleTitleTest@5e5792a0]" name="setUp" is-config="true" duration-ms="10799" started-at="2018-12-14T09:26:42Z" finished-at="2018-12-14T09:26:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="titleTest()[pri:0, instance:com.testPackage.GoogleTitleTest@5e5792a0]" name="titleTest" duration-ms="33" started-at="2018-12-14T09:26:53Z" finished-at="2018-12-14T09:26:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test Case is Failed expected [Googlee] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test Case is Failed expected [Googlee] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.testPackage.GoogleTitleTest.titleTest(GoogleTitleTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.testPackage.GoogleTitleTest@5e5792a0]" name="tearDown" is-config="true" duration-ms="624" started-at="2018-12-14T09:26:53Z" finished-at="2018-12-14T09:26:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.testPackage.GoogleTitleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
